[package]
name = "proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.4.1"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
# strip = "symbols"
