[package]
name = "aws-lambda-proxy"
version = "0.1.0"
edition = "2021"
description = "AWS Lambda HTTP(S) proxy."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/pillargg/proxy"
# documentation = "https://docs.rs/aws-lambda-proxy"
readme = "README.md"
license = "AGPL-3.0-only"
keywords = ["aws", "lambda", "http"]
categories = ["web-programming", "web-programming::http-server"]

[dependencies]
lambda_http = "0.4.1"
lambda_runtime = "0.4.1"
tokio = "1.13.0"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[features]
# strip = "symbols"
