[package]
name = "aws-lambda-relay"
version = "0.1.0"
edition = "2021"
description = "HTTP relay for AWS Lambda."
authors = ["Teddy Byron <ted@tedbyron.com>"]
repository = "https://github.com/pillargg/relay"
# documentation = "https://docs.rs/aws-lambda-relay"
readme = "README.md"
license = "AGPL-3.0-only"
keywords = ["aws", "lambda", "http"]
categories = ["web-programming::http-client", "network-programming"]

[features]

[dependencies]
hyper = "0.14.14"
lambda_http = "0.4.1"
tokio = "1.13.0"
tracing = "0.1.29"

[profile.dev]
debug = 0

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
# strip = "symbols"
