name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_and_lint:
    name: Check and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Cargo clippy
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
      - uses: actions-rs/cargo@v1
        name: Cargo test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Rustfmt
        with:
          command: fmt
          args: --all -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Cargo build
        with:
          command: build
          args: --release
